services:
  web1:
    build: .
    container_name: fastapi_service_1
    env_file:
      - .env
    expose:
      - "8008"
    volumes:
      - .:/app              
      - ./service:/app/service
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  web2:
    build: .
    container_name: fastapi_service_2
    env_file:
      - .env
    expose:
      - "8008"
    volumes:
      - .:/app              
      - ./service:/app/service
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web1
      - web2
    restart: unless-stopped
