"""upd

Revision ID: 6fab15271046
Revises: 965c0eeeb19f
Create Date: 2025-07-03 20:25:47.559112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fab15271046'
down_revision: Union[str, Sequence[str], None] = '965c0eeeb19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('intent', sa.Enum('PURCHASE', 'CHECK_STOCK', 'LIST_PRODUCTS', 'UNKNOWN', name='userintent'), nullable=False))
    op.add_column('transactions', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'confidence')
    op.drop_column('transactions', 'intent')
    # ### end Alembic commands ###
